### ISSUE TITLE
执行请求失败java.lang.IllegalArgumentException: Illegal character in path at index 2: NO MATCH

### ISSUE THREAD

**Issue by RingoTC** [liurijin123/LibReserve#4]
在发送GET请求这一步就失败了。
![image](https://user-images.githubusercontent.com/6525061/96953671-45dc3f00-1524-11eb-8941-1b14a0d53220.png)

Windows 平台。

**Comment by liurijin123** [comment]
开发了一个桌面版，想用的加qq群 1160811045
